### ISSUE TITLE
Engine to-do

### ISSUE THREAD

**Issue by demiurghg** [demiurghg/IronStar#103]
- [x] Surface/Render Target Manager
- [ ] SRgb & UAV support for each surface _(new branch!)_
- [x] Host-Service architecture _(new branch!)_:
  - [x] Attach
  - [x] Configure + Shell
  - [x] Update
  - [x] Dispose
  - [x] Service, RenderService, GameService(?)
- [ ] Better content pipeline _(new branch!)_: 
  - [ ] Content project file
- [x] Megatexture:
  - [x] Megatexture must be built from materials both from Maya and Substance Painter.
  - [x] Megatexture must use local paths for each scene.
- [ ] Installer
- [x] Fog & Sky
  - [x] Volume texture with compute support
  - ~~Fog volumes: density, self-illumination, absorption, sphere, cube, gradient~~
  - ~~Global fog (height, gradient, density)~~
  - ~~Render volumes to projection-space grid (64x64x64)~~
  - ~~Pre-integrate fog values~~
  - ~~Render scene using computed fog~~
  - ~~Custom sky setup (zenith gradient + solar gradient + custom colors)~~
  - [x] Exponential fog
- [x] Transparent objects:
  - [x] Megatexture
  - [x] Forward pass
  - [x] Distortive objects
- [ ] Particles:
  - [ ] Initial position distribution: [w,h,d], rectangle, sphere, cylinder, radial, radial gaussian.
  - [x] Distortive particles
  - [ ] Force field / volumes / trubulency
- [x] GI solution:
  - [x] GI-volumes: world space grid that contains sky visibility (dir + percentage).
  - [x] Compute ambient level for each point of visible GI-volume _(how?)_.
  - [x] Render scene using GI-volume
  - [x] Pre-render grayscale _(?)_ cubemaps, prefilter and scale them using data in GI-volumes.
