### ISSUE TITLE
Behavior tree

### ISSUE THREAD

**Issue by demiurghg** [demiurghg/IronStar#141]
**References**
1. [Gamasutra: Behavior trees for AI: How they work](https://www.gamasutra.com/blogs/ChrisSimpson/20140717/221339/Behavior_trees_for_AI_How_they_work.php)
2. [GameDev.ru: Behavior Trees in Unreal Engine 4](https://gamedev.ru/code/articles/unreal_bt#p3__spetsial_naya_obrabotka_dlya_par)
3. [GitHub: Fluent-Behaviour-Tree](https://github.com/ashleydavis/Fluent-Behaviour-Tree)

**Todo**

- [ ] BT tree and nodes
- [ ] BT tree processor
- [ ] Monster controller
- [ ] Environment query
  - [ ] Navigation
  - [ ] Visibility
- [ ] _BT description format_
- [ ] Blackboard
- [ ] Cooperation controller _(blackboard?)_
