### ISSUE TITLE
Redesign GameWorld and Entities

### ISSUE THREAD

**Issue by demiurghg** [demiurghg/IronStar#187]
_Write your code for this game only — not for future game. You're going to be writing new code later because you'll be smarter._ — John Romero

### Tasks
- [ ] Remove client-server related stuff
  - [ ] Atoms
  - [x] Player connections, disconnections etc
- [ ] Aggregate view models and SFX to entities
  - [ ] Characters
  - [ ] Weapon model
  - [ ] Box
  - [ ] Projectiles
- [ ] Add entity (and item) activation/deactivation routine (?)
- [ ] Add save/load functionality

#### Tips
- Keep Items and Entities the same as before, they are good enough

### Requirements

1. Meet single-player architecture #155 
2. Meet multi-player architecture in future. See citation.
3. No ECS, no other fansy stuff, just aggregation.
4. Fixed time-step for simulation and update/

### Possible solutions

1. Game world inheritance, i.e.:
```csharp
abstract class GameWorld {
  void Simulate ( GameTime gameTime );
  void Present ( GameTime gameTime );
}
class MPGameWorld : GameWorld {}
class SPGameWorld : GameWorld {}
```
2. Entities defines rules: _(Quake 1,2,3)_
3. Triggers defines entire world behavior: _(Starcraft)_
4. Just remove unnecessary stuff... 

### References

- [Writing a Game Engine in 2017](https://www.randygaul.net/2017/02/24/writing-a-game-engine-in-2017/)
- [Introductory bullshit detection for non-technical managers](https://itsyourturnblog.com/introductory-bullshit-detection-for-non-technical-managers-7c7a9e54afee)
