### ISSUE TITLE
Shading visualization

### ISSUE THREAD

**Issue by demiurghg** [demiurghg/IronStar#192]
- [ ] ~~Diffuse albedo (after decals)~~ (moved to #193)
- [ ] ~~World normal (after decals)~~ (moved to #193)
- [ ] ~~Roughness/Metallic~~ (moved to #193)
- [x] White diffuse (throw virtual texture)
- [x] White glossy specular (throw virtual texture)
